/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logy;

/**
 *
 * @author Chinnmay
 */
public class order extends javax.swing.JFrame {

    /**
     * Creates new form order
     */
    public order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        place_order = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        place_order.setText("Place Order");
        getContentPane().add(place_order);
        place_order.setBounds(747, 455, 115, 29);

        cancel.setText("Cancel Order");
        getContentPane().add(cancel);
        cancel.setBounds(315, 455, 125, 29);

        jLabel1.setText("Estimated Time");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 290, 120, 20);

        jLabel2.setText("Reciver Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 50, 200, 20);

        jLabel3.setText("Sender Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 50, 200, 20);

        jLabel4.setText("Order Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 180, 110, 20);

        jLabel5.setText("Order Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 50, 200, 20);

        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 240, 70, 20);

        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 100, 41, 20);

        jLabel8.setText("Number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 150, 70, 20);

        jLabel9.setText("City");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 190, 70, 20);

        jLabel10.setText("Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 110, 41, 20);

        jLabel11.setText("Number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 160, 70, 20);

        jLabel12.setText("City");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 200, 70, 20);

        jLabel13.setText("Order ID");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(620, 130, 110, 20);

        jLabel14.setText("Cost");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(620, 240, 40, 20);

        jLabel15.setText("SetName");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(140, 110, 90, 20);

        jLabel16.setText("setNumber");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(140, 160, 70, 20);

        jLabel17.setText("setCity");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(140, 200, 70, 20);

        jLabel18.setText("setAddress");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(450, 240, 70, 20);

        jLabel19.setText("setName");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(450, 100, 100, 20);

        jLabel20.setText("setNumber");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(450, 150, 70, 20);

        jLabel21.setText("setCity");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(450, 190, 70, 20);

        jLabel22.setText("setEstimated Time");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(770, 290, 120, 20);

        jLabel23.setText("setOrder Type");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(770, 180, 110, 20);

        jLabel24.setText("setOrder ID");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(780, 130, 110, 20);

        jLabel25.setText("setCost");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(780, 240, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton place_order;
    // End of variables declaration//GEN-END:variables
}
