/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trialapp;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import java.awt.Desktop;
import static java.awt.Desktop.getDesktop;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author ROHIT
 */
public class orderSummary extends javax.swing.JFrame {

    /**
     * Creates new form orderSummary
     */
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
         static final String DB_URL = "jdbc:mysql://localhost:3306/logistics";
         String bookname,booknumber,bookcity;
         String order_id = null;
         int prod_id = 0;
    public orderSummary() {
        initComponents();
          getData();
          getpdf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        senderName = new javax.swing.JLabel();
        senderNumber = new javax.swing.JLabel();
        senderEmail = new javax.swing.JLabel();
        senderCity = new javax.swing.JLabel();
        recieverName = new javax.swing.JLabel();
        recieverNumber = new javax.swing.JLabel();
        recieverEmail = new javax.swing.JLabel();
        productDesc = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        recieverAddress = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDER SUMMARY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 50, 450, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ORDER ID:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 140, 100, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SENDER NAME:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 250, 120, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SENDER NUMBER:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 300, 150, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SENDER E-MAIL:-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 340, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("SENDER CITY:-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 380, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("RECEIVER NAME:-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(760, 250, 160, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("RECEIVER NUMBER:-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 290, 160, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("RECEIVER E-MAIL:-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(760, 340, 150, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("RECEIVER ADDRESS:-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(760, 420, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("PRODUCT DESCRIPTION:-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 500, 200, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ESTIMATED COST:-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 570, 140, 50);
        getContentPane().add(orderLabel);
        orderLabel.setBounds(610, 150, 230, 40);
        getContentPane().add(senderName);
        senderName.setBounds(440, 250, 180, 40);
        getContentPane().add(senderNumber);
        senderNumber.setBounds(440, 300, 180, 40);
        getContentPane().add(senderEmail);
        senderEmail.setBounds(440, 340, 200, 40);
        getContentPane().add(senderCity);
        senderCity.setBounds(440, 380, 200, 40);

        recieverName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recieverNameKeyTyped(evt);
            }
        });
        getContentPane().add(recieverName);
        recieverName.setBounds(940, 250, 210, 40);
        getContentPane().add(recieverNumber);
        recieverNumber.setBounds(940, 300, 210, 40);
        getContentPane().add(recieverEmail);
        recieverEmail.setBounds(940, 340, 190, 40);
        getContentPane().add(productDesc);
        productDesc.setBounds(540, 510, 240, 40);
        getContentPane().add(costLabel);
        costLabel.setBounds(570, 570, 80, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("PLACE ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(860, 630, 150, 50);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(310, 630, 130, 50);
        getContentPane().add(recieverAddress);
        recieverAddress.setBounds(950, 410, 240, 130);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK TO BOOKING PORTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 630, 260, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trialapp/ornament_background_light_texture_50484_1920x1080_1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1360, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Connection conn = null;
         Statement stmt = null;
         ResultSet rs=null;
         try{
         Class.forName("com.mysql.jdbc.Driver");
         conn = DriverManager.getConnection(DB_URL,"root","R30101997c");
         stmt=conn.createStatement();        
        JOptionPane.showMessageDialog(null, "ORDER PLACED SUCCESFULLY");
        //String query="DROP TABLE booking";
        //stmt.executeUpdate(query);
        File f=new File("C:\\Users\\ROHIT\\Documents\\NetBeansProjects\\trialapp\\Invoices\\"+"INVOICE_"+orderLabel.getText()+".pdf");
    Desktop d=getDesktop();
            
                d.open(f);
            
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
            bookingFirst obj=new bookingFirst();
            obj.setVisible(true);
            obj.setTitle("BOOKING LANDING PAGE");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.dispose();
        productFrame obj=new productFrame();
        obj.setTitle("PRODUCT DETAILS");
        obj.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
         Statement stmt = null;
         ResultSet rs=null;
         try{
         Class.forName("com.mysql.jdbc.Driver");
         conn = DriverManager.getConnection(DB_URL,"root","R30101997c");
         stmt=conn.createStatement();
         String query="DELETE FROM ORDERS WHERE order_id="+order_id;
         stmt.executeUpdate(query);
         query="delete from product where product_id="+prod_id;
         stmt.executeUpdate(query);
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         this.dispose();
         bookingFirst obj=new bookingFirst();
            obj.setVisible(true);
            obj.setTitle("BOOKING LANDING PAGE");
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void recieverNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recieverNameKeyTyped

    }//GEN-LAST:event_recieverNameKeyTyped

    public void operatorDetails()
    {
        Connection conn = null;
         Statement stmt = null;
         ResultSet rs=null;
         try{
         Class.forName("com.mysql.jdbc.Driver");
         conn = DriverManager.getConnection(DB_URL,"root","R30101997c");
         stmt=conn.createStatement();
         String query="Select *from booking";
         rs=stmt.executeQuery(query);
         while(rs.next())
         {
             bookname=rs.getString("name");
             booknumber=rs.getString("number");
             bookcity=rs.getString("city");
         }
         
         
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void getData()
    {
        Connection conn = null;
         Statement stmt = null;
         ResultSet rs=null;
         String sender_num = null;
         String sender_name = null;
         String reciever_num = null;
         String sender_email = null;
         String reciever_name = null;
         String reciever_email = null;
         String sender_city = null;
         String reciever_address = null;
         String product_desc = null;
         int cost = 0;
         double time = 0;
        
         try{
         Class.forName("com.mysql.jdbc.Driver");
         conn = DriverManager.getConnection(DB_URL,"root","R30101997c");
         stmt=conn.createStatement();
         String query="select *from orders where order_id=(select max(order_id) from orders)";
         rs=stmt.executeQuery(query);
         while(rs.next())
         {
             order_id=rs.getString("order_id");
             sender_num=rs.getString("sender_number");
             reciever_num=rs.getString("reciever_number");
             cost=Integer.parseInt(rs.getString("cost"));
             time=Double.parseDouble(rs.getString("delivery_time"));
             prod_id=Integer.parseInt(rs.getString("product_id"));
         }
         
         
         String query2="SELECT *FROM SENDER WHERE number="+"'"+sender_num+"'";
         rs=stmt.executeQuery(query2);
         while(rs.next())
         {
             sender_name=rs.getString("name");
             sender_email=rs.getString("email");
             sender_city=rs.getString("city");

         }
         
         String query3="SELECT *FROM RECIEVER WHERE number="+"'"+reciever_num+"'";
         rs=stmt.executeQuery(query3);
         while(rs.next())
         {
             reciever_name=rs.getString("name");
             reciever_email=rs.getString("email");
             reciever_address=rs.getString("address");

         }
         
         String query4="SELECT description FROM product WHERE product_id="+prod_id;
         rs=stmt.executeQuery(query4);
         while(rs.next())
         {
             product_desc=rs.getString("description");

         }
         
         
         senderName.setText(sender_name);
         senderNumber.setText(sender_num);
         senderEmail.setText(sender_email);
         senderCity.setText(sender_city);
         
         recieverName.setText(reciever_name);
         recieverNumber.setText(reciever_num);
         recieverEmail.setText(reciever_email);
         recieverAddress.setText(reciever_address);
         
         productDesc.setText(product_desc);
         costLabel.setText(String.valueOf(cost));
         //timeDeliver.setText(String.valueOf(time));
         
         orderLabel.setText(order_id);
         
         
         
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orderSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         finally{
                //finally block used to close resources
                try{
                    if(stmt!=null)
                    conn.close();
                }catch(SQLException se){
                }// do nothing
                try{
                    if(conn!=null)
                    conn.close();
                }catch(SQLException se){
                    se.printStackTrace();
                }
                
         }
         
         
         
    }
    
    
    public void getpdf()
    {
        Document doc=new Document();
        try {
            PdfWriter.getInstance(doc,new FileOutputStream("C:\\Users\\ROHIT\\Documents\\NetBeansProjects\\trialapp\\Invoices\\INVOICE_"+orderLabel.getText()+".pdf"));
            doc.open();
            operatorDetails();
            doc.addTitle("INVOICE_"+orderLabel.getText());
            
            doc.add(new Paragraph("                                     INVOICE",FontFactory.getFont(FontFactory.TIMES_ROMAN,22, Font.BOLD, BaseColor.BLACK)));
             doc.add(new Paragraph("\n"));
            doc.add(new Paragraph("                                                   OPERATOR DETAILS:-",FontFactory.getFont(FontFactory.TIMES_ROMAN,14, Font.BOLD, BaseColor.BLACK)));
            doc.add(new Paragraph("NAME:-      "+bookname));
            doc.add(new Paragraph("NUMBER:-  "+booknumber));
            doc.add(new Paragraph("CITY:-        "+bookcity));
            Chunk linebreak = new Chunk(new DottedLineSeparator());
           doc.add(linebreak);
           
           doc.add(new Paragraph("                                                      SENDER DETAILS:-",FontFactory.getFont(FontFactory.TIMES_ROMAN,14, Font.BOLD, BaseColor.BLACK)));
            
            doc.add(new Paragraph(jLabel2.getText()+"    "+orderLabel.getText()));
            doc.add(new Paragraph(jLabel3.getText()+"    "+senderName.getText()));
            doc.add(new Paragraph(jLabel4.getText()+"    "+senderNumber.getText()));
            doc.add(new Paragraph(jLabel5.getText()+"    "+senderEmail.getText()));
            doc.add(new Paragraph(jLabel6.getText()+"    "+senderCity.getText()));
            
            doc.add(linebreak);
            doc.add(new Paragraph("                                                      RECIEVER DETAILS:-",FontFactory.getFont(FontFactory.TIMES_ROMAN,14, Font.BOLD, BaseColor.BLACK)));
            
            
            doc.add(new Paragraph(jLabel7.getText()+"    "+recieverName.getText()));
            doc.add(new Paragraph(jLabel8.getText()+"    "+recieverNumber.getText()));
            doc.add(new Paragraph(jLabel9.getText()+"    "+recieverEmail.getText()));
            doc.add(new Paragraph(jLabel10.getText()+"    "+recieverAddress.getText()));
            
            doc.add(linebreak);
             doc.add(new Paragraph("                                                        PRODUCT DETAILS:-",FontFactory.getFont(FontFactory.TIMES_ROMAN,14, Font.BOLD, BaseColor.BLACK)));
            doc.add(new Paragraph(jLabel11.getText()+"    "+productDesc.getText()));
            doc.add(new Paragraph("COST:-"+"    "+"Rs."+costLabel.getText(),FontFactory.getFont(FontFactory.defaultEncoding,14, Font.BOLD, BaseColor.BLACK)));
            doc.add(linebreak);
            doc.add(new Paragraph("\n"));
            
            doc.add(new Paragraph("                                                              THANK YOU!",FontFactory.getFont(FontFactory.TIMES_ROMAN,14, Font.BOLD, BaseColor.BLACK)));
            doc.add(new Paragraph("\n"));
            doc.add(new Paragraph("                                                                                                                            SIGNATURE"));
            
            
            doc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(productFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(productFrame.class.getName()).log(Level.SEVERE, null, ex);
        
    }                                          
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               orderSummary obj=new orderSummary();
               obj.setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel costLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel productDesc;
    private javax.swing.JLabel recieverAddress;
    private javax.swing.JLabel recieverEmail;
    private javax.swing.JLabel recieverName;
    private javax.swing.JLabel recieverNumber;
    private javax.swing.JLabel senderCity;
    private javax.swing.JLabel senderEmail;
    private javax.swing.JLabel senderName;
    private javax.swing.JLabel senderNumber;
    // End of variables declaration//GEN-END:variables
}
