 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trialapp;

import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;

/**
 *
 * @author ROHIT
 */
public class productFrame extends javax.swing.JFrame {

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/logistics";
    /**
     * Creates new form productFrame
     */
    public productFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        descLabel = new javax.swing.JLabel();
        fragileLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descText = new javax.swing.JTextArea();
        weightText = new javax.swing.JTextField();
        volumeText = new javax.swing.JTextField();
        yesRadio = new javax.swing.JRadioButton();
        noRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        errorVolume = new javax.swing.JLabel();
        errorWeight = new javax.swing.JLabel();
        descError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        descLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        descLabel.setText("DESCRIPTION:-");
        getContentPane().add(descLabel);
        descLabel.setBounds(370, 260, 160, 50);

        fragileLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fragileLabel.setText("FRAGILE:-");
        getContentPane().add(fragileLabel);
        fragileLabel.setBounds(430, 480, 100, 40);

        volumeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        volumeLabel.setText("LARGEST DIMENSION:-");
        getContentPane().add(volumeLabel);
        volumeLabel.setBounds(310, 350, 220, 50);

        weightLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        weightLabel.setText("WEIGHT:-");
        getContentPane().add(weightLabel);
        weightLabel.setBounds(430, 420, 100, 40);

        descText.setColumns(20);
        descText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descText.setRows(5);
        descText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                descTextFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(descText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 250, 350, 70);

        weightText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        weightText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                weightTextFocusLost(evt);
            }
        });
        weightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextActionPerformed(evt);
            }
        });
        weightText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weightTextKeyTyped(evt);
            }
        });
        getContentPane().add(weightText);
        weightText.setBounds(550, 420, 110, 40);

        volumeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        volumeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                volumeTextFocusLost(evt);
            }
        });
        volumeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextActionPerformed(evt);
            }
        });
        volumeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                volumeTextKeyTyped(evt);
            }
        });
        getContentPane().add(volumeText);
        volumeText.setBounds(550, 360, 110, 40);

        yesRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yesRadio.setText("YES");
        yesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioActionPerformed(evt);
            }
        });
        getContentPane().add(yesRadio);
        yesRadio.setBounds(550, 490, 60, 25);

        noRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noRadio.setText("NO");
        noRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioActionPerformed(evt);
            }
        });
        getContentPane().add(noRadio);
        noRadio.setBounds(650, 490, 60, 25);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCT  DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 80, 350, 80);

        nextButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(940, 590, 120, 40);

        errorLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorLabel);
        errorLabel.setBounds(780, 470, 290, 50);

        errorVolume.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorVolume.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorVolume);
        errorVolume.setBounds(790, 360, 210, 40);

        errorWeight.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorWeight.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorWeight);
        errorWeight.setBounds(780, 420, 210, 40);

        descError.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        descError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(descError);
        descError.setBounds(950, 250, 190, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("(in kg)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 420, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("(in metres)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 360, 110, 40);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(400, 590, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trialapp/68635516-logistics-wallpapers_1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volumeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeTextActionPerformed

    private void weightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextActionPerformed

    private void yesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioActionPerformed
        
        
    }//GEN-LAST:event_yesRadioActionPerformed

    private void noRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noRadioActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
         
        float volume = 0,weight = 0;
        String description=descText.getText();
        int flag=0;
        if(volumeText.getText().equals(""))
        {
            errorVolume.setText("*Enter volume value");
            flag=1;
        }
        else
        {
        volume=Float.parseFloat(volumeText.getText());
        }
        
        if(weightText.getText().equals(""))
        {
            errorWeight.setText("*Enter weight value");
            flag=1;
        }
        else
        {
        weight=Float.parseFloat(weightText.getText());
        }
        
        String value = null;
        if(yesRadio.isSelected()&&!(noRadio.isSelected()))
        {
            value=yesRadio.getText();
        }
        
        else if(noRadio.isSelected()&&!(yesRadio.isSelected()))
        {
            value=noRadio.getText();
            
        }
        
        else if(noRadio.isSelected()&&yesRadio.isSelected())
        {
            errorLabel.setText("*Select only one fragility attribute");
            value="";
        }
        else{
            value="";
            errorLabel.setText("*Select appropriate fragility attribute");
        }
        
        if(!(value.equals("")&&flag==1))
        {
        char v=value.charAt(0);
        
        
        Connection conn = null;
         Statement stmt = null;
         ResultSet rs=null;
         try{
         Class.forName("com.mysql.jdbc.Driver");
         conn = DriverManager.getConnection(DB_URL,"root","R30101997c");
         stmt=conn.createStatement();
         
         String query="SELECT max(product_id) from orders";
         rs=stmt.executeQuery(query);
         int prod_id = 0;
         while(rs.next())
         {
             prod_id=Integer.parseInt(rs.getString("max(product_id)"));
         }
         System.out.println(prod_id);
         
         String query2="UPDATE product SET volume="+volume+", weight="+weight+", description="+"'"+description+"'"+", fragile="+"'"+v+"'"+" WHERE product_id="+prod_id;
         System.out.println(query2);
         stmt.executeUpdate(query2);
         
         String query3="SELECT s.city FROM sender s, orders o WHERE o.sender_number=s.number AND o.product_id="+prod_id;
         rs=stmt.executeQuery(query3);
         
         String send_city = null,rec_city = null;
         while(rs.next())
         {
            send_city=rs.getString("city");
             
         }
         System.out.println(send_city);
         
         String query4="SELECT r.city FROM reciever r, orders o WHERE o.reciever_number=r.number AND o.product_id="+prod_id;
         rs=stmt.executeQuery(query4);
         while(rs.next())
         {
            rec_city=rs.getString("city");
             
         }
         System.out.println(rec_city);
         
         String query5="SELECT "+send_city+" from time_graph WHERE city_name="+"'"+rec_city+"'";
         rs=stmt.executeQuery(query5);
         System.out.println(query5);
         
         float distcity= (float) 0.0;
         while(rs.next())
         {
             distcity=Float.parseFloat(rs.getString(send_city));
             
         }
         System.out.println(distcity);
         
         int cost=0;
         
         cost=(int)(weight*50+volume*50+((distcity-Math.floor(distcity))*100)+((distcity-(distcity-Math.floor(distcity)))*10000));
         System.out.println(cost);
         String query6="UPDATE orders SET cost="+cost+" WHERE product_id="+prod_id; 
         stmt.executeUpdate(query6);

         
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(productFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(productFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            conn.close();
      }catch(SQLException se){
      }// do nothing
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
         se.printStackTrace();
      }
         }
        
                  this.dispose();
                  orderSummary obj=new orderSummary();
                  obj.setVisible(true);
                  obj.setTitle("ORDER SUMMARY");
        }
         
    }//GEN-LAST:event_nextButtonActionPerformed
                  
    
    private void descTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descTextFocusLost

        if(descText.getText().equals(""))
        descError.setText("*Enter the description");
        else
            descError.setText("");
    }//GEN-LAST:event_descTextFocusLost

    private void volumeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_volumeTextFocusLost

        if(volumeText.getText().equals(""))
            errorVolume.setText("*Enter the volume");
            else
            errorVolume.setText("");
    }//GEN-LAST:event_volumeTextFocusLost

    private void weightTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightTextFocusLost

        if(weightText.getText().equals(""))
            errorWeight.setText("*Enter the weight");
            else
            errorWeight.setText("");
    }//GEN-LAST:event_weightTextFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.dispose();
        Sender obj=new Sender();
        obj.setTitle("USER DETAILS PAGE");
        obj.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void volumeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_volumeTextKeyTyped
        
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)||ch=='.'))
            evt.consume();
    }//GEN-LAST:event_volumeTextKeyTyped

    private void weightTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightTextKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)||ch=='.'))
            evt.consume();
    }//GEN-LAST:event_weightTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                productFrame pf=new productFrame();
                pf.setTitle("PRODUCT DETAILS");
                pf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel descError;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextArea descText;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorVolume;
    private javax.swing.JLabel errorWeight;
    private javax.swing.JLabel fragileLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton noRadio;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JTextField volumeText;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightText;
    private javax.swing.JRadioButton yesRadio;
    // End of variables declaration//GEN-END:variables
}
